return {
    -- {
    --     "roobert/tailwindcss-colorizer-cmp.nvim",
    --     -- optionally, override the default options:
    --     config = function()
    --         require("tailwindcss-colorizer-cmp").setup({
    --             color_square_width = 2,
    --         })
    --     end
    -- },
    -- {
    --     "NvChad/nvim-colorizer.lua",
    --     dependencies = { "nvim-treesitter/nvim-treesitter" },
    --     opts = {},
    --     config = function()
    --         local nvchadcolorizer = require("colorizer")
    --         local tailwindcolorizer = require("tailwindcss-colorizer-cmp")
    --
    --         nvchadcolorizer.setup({
    --             user_default_options = {
    --                 tailwind = true,
    --             },
    --             filetypes = { "html", "css", "typescript", "jsx", "tsx", "vue", "svelte" },
    --         })
    --
    --         tailwindcolorizer.setup({
    --             color_square_width = 2,
    --         })
    --     end,
    -- },
}
